### ISSUE TITLE
Readme file add deployment instructions

### ISSUE THREAD

**Issue by valchkou** [99Niki99/ThirdWheelBotTG#1]
details.

Acceptance criteria

**Comment by ekbduffy** [comment]
I'd suggest updating from plaintext to markdown. This will let you to format the text as well as possibly add ariel-diagrams.

**Comment by ekbduffy** [comment]
Additionally, i would recommend having some structure in the readme like:
# repo name
short description of the whole project
## how to run
## how to test
## explanation of the processes with diagrams if needed
## how to contribute

**Comment by 99Niki99** [comment]
@ekbduffy  make readme, please check
