### ISSUE TITLE
common-login.jar conflict

### ISSUE THREAD

**Issue by 99Niki99** [99Niki99/ThirdWheelBotTG#10]
Такая проблема
![image](https://github.com/99Niki99/ThirdWheelBotTG/assets/96220339/99f169be-c6a1-4287-962a-74c6978eb6ef)
Решил пройти методом от противного, дал исключения во все депенденси мавена. Ошибка не высвечивалась, но он все равно не запускается с таким сообщением :
![image](https://github.com/99Niki99/ThirdWheelBotTG/assets/96220339/544880f0-cb84-4de8-a864-a78816181ffd)
удалял исключение из каждого наследования, пока не нашел то, при котором commons-logging выскакивает снова. 
Вот это наследование:
![image](https://github.com/99Niki99/ThirdWheelBotTG/assets/96220339/f6e58f8a-3b0b-416f-81f8-f19f27e154dc)

**Comment by valchkou** [comment]
spring start failure is not connected to common-logging. There must be something else.
Start your app with debug.
https://docs.spring.io/spring-boot/docs/1.5.22.RELEASE/reference/html/boot-features-logging.html#boot-features-logging-console-output

**Comment by 99Niki99** [comment]
Done
