### ISSUE TITLE
Refactor TelegramBot.java

### ISSUE THREAD

**Issue by valchkou** [99Niki99/ThirdWheelBotTG#4]
- constructor injection for all required dependencies
-  declare injected properties as "private final"
- inject AutomatedReminderServiceTGBot as service
- redundant method: startCommandReceived, use sendMessage instead
- code below must be encapsulated inside AutomatedReminderServiceTGBot
```
                List<String> txt =  automatedReminderServiceTGBot.separateMsg(messageText);
                automatedReminderServiceTGBot.putReminderInData(txt);
                automatedReminderServiceTGBot.sendReminder(txt);
```

**Comment by 99Niki99** [comment]
https://github.com/99Niki99/ThirdWheelBotTG/compare/master...4-refactor-telegrambotjava
Check Please

**Comment by 99Niki99** [comment]
@valchkou check please
